# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "knitr", "magick")); devtools::install_deps("1.3-0/popdemo")'
script:
  - Rscript -e 'devtools::check("1.3-0/popdemo")'


# R versions
r:
  - release

# operating systems to test. Excluding r-devel
os:
  - linux
  - osx

# options for Linux tests
sudo: false
dist: trusty
cache: packages

