# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

# R versions
r:
  - oldrel
  - release

# operating systems to test. Excluding r-devel
os:
  - linux
  - osx

# options for Linux tests
sudo: false
dist: trusty
cache: packages

